#cloud-config

package_update: true
package_upgrade: true
packages:
  - httpd

write_files:
  - path: /var/www/html/index.html
    content: |
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <title>Cloud config</title>
      </head>
      <body>
        <h1>MY APACHE SERVER via CLOUD CONFIG</h1>
      </body>
      </html>
    owner: root:root
    permissions: '0644'
runcmd:
  - systemctl start httpd.service
  - systemctl enable httpd.service
  - systemctl restart httpd.service
