#!/usr/bin/env bash
echo "> deploy-bucket-via-cfn"

STACK_NAME="cfn-s3-simple"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudformation/deploy.html
aws cloudformation deploy \
  --template-file template.yaml \
  --no-execute-changeset \
  --region ap-south-1 \
  --stack-name $STACK_NAME
