#!/usr/bin/env bash
echo "> create-bucket"

# check for bucket name
if [ -z "$1" ]; then
  echo "Bucket name is required, eg. my-bucket-name"
  exit 1
fi

BUCKET_NAME="$1"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/create-bucket.html
CMD="aws s3api create-bucket \
  --bucket \"$BUCKET_NAME\" \
  --create-bucket-configuration="LocationConstraint=ap-south-1" \
  --query Location \
  --output text"

echo

if eval "$CMD"; then
  echo "Created bucket: $BUCKET_NAME"
fi
