#!/usr/bin/env bash
echo "> delete-bucket"

# check for bucket name
if [ -z "$1" ]; then
  echo "Bucket name is required, eg. my-bucket-name"
  exit 1
fi

BUCKET_NAME="$1"

# https://awscli.amazonaws.com/v2/documentation/api/latest/reference/s3api/delete-bucket.html
CMD="aws s3api delete-bucket \
  --bucket \"$BUCKET_NAME\" \
  --output text"

echo

if eval "$CMD"; then
  echo "Deleted bucket: $BUCKET_NAME"
fi
